## Heroes
combobox_awakened = ["aTalene", "aEzizh", "aThane", "aBrutus", "aSolise", "aBaden", "aAthalia", "Maetria", "aBelinda", "aSafiya", "aLyca", "aShemira", "Gavus", "Eugene", "aLucius", "aAntandra", "aEironn", "aThoran", "Zohra", "Envydiel", "aEstrilda", "None"]
combobox_celepog = ["Athalia", "Ezizh", "Mehira", "Twins", "Zolrath", "Orthros", "Talene", "Wukong", "Khazard", "Mezoth", "Flora", "Zaphrael", "Lucretia", "Mortas", "Alna", "Morael", "Leofric", "Titus", "Zikis", "Haelus", "Framton", "Audrae", "Vyloris", "Tarnos", "Canisa&Ruke", "Veithael", "Olgath", "Daemia", "Liberta", "Lucilla", "Lavatune", "Malkrie", "Kalthin", "Aurelia", "Knox", "Lysander", "Serenmira", "None"]
combobox_4f = ["Estrilda", "Belinda", "Raine", "Fawkes", "Lucius", "Thane", "Hendrik", "Rowan", "Gwyneth", "Rosaline", "Cecilia", "Rigby", "Oscar", "Eluard", "Peggy", "Walker", "Morrow", "Scarlet", "Thane", "Sonja", "Palmer", "Ginneas", "Jerome", "Adrian", "Raoul", "Alvida", "Brutus", "Khasos", "Vurk", "Numisu", "Skreg", "Warek", "Antandra", "Safiya", "Satrana", "Tidus", "Drez", "Skriath", "Anoki", "Kren", "Thali", "Granit", "Thesku", "Alaro", "Anasta", "Salaki", "Crassio", "Naroko", "Vika", "Villanelle", "Gorren", "Nemora", "Kaz", "Lyca", "Tasi", "Ulmus", "Seirus", "Eironn", "Gorvo", "Lorsan", "Saurus", "Solise", "Pippa", "Respen", "Raku", "Mishka", "Astar", "Oku", "Eorin", "Nevanthi", "Tamrus", "Trishea", "Atheus", "Misha", "Grezhul", "Shemira", "Thoran", "Isabella", "Nara", "Ferael", "Baden", "Kelthur", "Silas", "Oden", "Izold", "Torne", "Daimon", "Theowyn", "Desira", "Hodgekin", "Treznor", "Fane", "Kalene", "Edwin", "Ivan", "Simona", "Bronn", "Randle", "Mira", "None"]

## Tap Locations
back_button = [30, 1890]
claim_afk_rewards_chest = [540, 1536]
collect_afk_rewards_button = [720, 1360]
campaign_screen_battle_button = [540, 1660]
campaign_multi_battle_button = [540, 1475]
start_battle_button = [610, 1830]
pause_battle_button = [75, 1460]
exit_battle_button = [260, 950]
fast_reward_button = [933, 1655]
claim_fast_rewards_button = [700, 1260]
banner_friends_button = [985, 765]
friends_send_and_receive_button = [888, 1630]
friends_mercenaries_button = [720, 1760]
friends_mercenaries_manage_button = [990, 190]
friends_mercenaries_apply_button = [590, 1600]
friends_mercenaries_send_button = [760, 1400]
banner_mail_button = [985, 580]
mail_claim_all_button = [800, 1600]
mail_delete_all_button = [300, 1600]
mail_delete_all_confirm_button = [700, 1260]
unlimited_summons_tap_next = [850, 1830]
unlimited_summons_tap_record = [400, 1830]
unlimited_summons_tap_replace = [720, 1550]